create table person(
   id int generated by default as identity primary key ,
   name varchar(100) not null,
   age int check ( age > 0 ),
   email varchar(100) unique,
   address varchar(200) not null
);
