drop table person;
create table person(
                       id int generated by default as identity primary key ,
                       name varchar(200),
                       age int
);

create table orders(
                       id int generated by default as identity primary key ,
                       person_id int references person(id),
                       item_name varchar(1024)
);

insert into person (name, age)
values ('Thomas', 25);

insert into orders(person_id, item_name) VALUES (1, 'Airpods');

delete from person where id = 1;

drop table orders;
create table orders(
                       id int generated by default as identity primary key ,
                       person_id int references person(id) on DELETE cascade ,
                       item_name varchar(1024)
);

select * from orders;
select * from person;

create table orders(
                       id int generated by default as identity primary key ,
                       person_id int references person(id) on DELETE set null ,
                       item_name varchar(1024)
);